apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-myapp

resources:
  - serviceaccount.yaml
  - external-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app: myapp
  environment: dev
  managed-by: argocd

images:
  - name: myacr.azurecr.io/myapp
    newTag: v1.0.0
